### PR TITLE
Add Python 3.6

### PR DESCRIPTION
**Pull request by hugovk**
Also test Travis CI on already supported 3.5.

### CODE REVIEW

**Comment by hugovk** [comment]
CI failure is unrelated to this PR.

**Comment by hugovk** [comment]
Updated to resolve conflict.

**Comment by rbtcollins** [comment]
Could you rebase this ? (and then push -f back to the same proposed branch)

**Comment by hugovk** [comment]
Rebased and force-pushed!

**Comment by cjw296** [comment]
What is the tox.ini actually used for? Seems to have diverged a lot from the .travis.yml...

**Comment by hugovk** [comment]
I guess `tox.ini` was added for local development. If people don't use it often, or it's not used for the CI, they do tend to get a bit outdated.

**Pull request merged**
