### PR TITLE
Fix reset_mock on mock with deleted children

### PR DESCRIPTION
**Pull request by eli-b**

### CODE REVIEW

**Comment by eli-b** [comment]
Can I please get feedback on this? It's been almost a year.

**Comment by cjw296** [comment]
@eli-b - why not get this fixed in https://github.com/python/cpython first? That's the "true source" for mock now, I'd imagine if you get it fixed there, a backport to this repo wouldn't be too traumatic.

**Comment by cjw296** [comment]
Indeed, this has not changed upstream, please get it fixed there and then we can backport.

**Comment by cjw296** [comment]
https://github.com/python/cpython/pull/9302

**Pull request closed without merging**
