### PR TITLE
Backporting - please don't merge!

### PR DESCRIPTION
**Pull request by cjw296**

### CODE REVIEW

**Comment by tirkarthi** [comment]
Thanks a lot @cjw296 for syncing this. I am not sure of the user base available to test this though mock is one of the most downloaded modules. Does an RC candidate for this release help in getting this tested by some projects? 

I think this would perhaps qualify as mock 3.0.0 🎉

**Comment by cjw296** [comment]
This is definitely 3.0.0 as it drops Py2.6 and 3.3 support. 

I don't believe in RCs ;-) If it breaks stuff, people can pin to 2.0.0 until we can fix it :-)

**Comment by rbtcollins** [comment]
Yes, dropping versions is a major version per semver rules. 

If we break things in unexpected ways, we can likely revert out just a couple of commits - but given we're only backporting, I would expect those to be pretty rare corner cases.

Thank you very much for this effort.

**Comment by rbtcollins** [comment]
Getting advance testing of this is pretty hard; you could ask in the #openstack-infra channel on freenode: they are a big user, and have fairly sophisticated CI - should be able to pull out of git if they desire.

**Comment by cjw296** [comment]
Feel free to get them to test current master, we're all up to date now.

**Pull request merged**
