### PR TITLE
Remove dead code from __init__.py

### PR DESCRIPTION
**Pull request by eli-b**

### CODE REVIEW

**Comment by rbtcollins** [comment]
This code isn't dead code AFAICT; what makes you say it is dead?

**Comment by eli-b** [comment]
@rbtcollins, it's commented out.

**Comment by rbtcollins** [comment]
oh heh, misread the diff. Thanks!

**Comment by eli-b** [comment]
Phew, I was afraid we were going to get into a philosophical argument :)

בתאריך יום ב׳, 12 בדצמ׳ 2016, 00:10, מאת Robert Collins ‏<
notifications@github.com>:

**Pull request merged**
