### PR TITLE
CI for packaging

### PR DESCRIPTION
**Pull request by cjw296**
...and the fixes it highlights!

NB: The commits on this PR will be a mess until they're merged. I need to trigger CI to test things.

### CODE REVIEW

**Comment by tirkarthi** [comment]
@cjw296 As a personal opinion can the commits be squashed and merged like CPython does for this PR. Helps in reading the commit list on master branch.

**Comment by cjw296** [comment]
@tirkarthi - I put a comment to explain the mess on this PR above, sorry for the confusion!

That said, I really value a `git blame` for a line explaining why code is the way it is.
That means I tend to develop on a branch, and then `git rebase -i` before merging such that each commit makes sense as one semantic change; I think this is what the python dev guide recommends?

Now, where I differ on that is, having gone to all that trouble, a squash merge then loses all that information and makes `git blame` much less useful. Personally, I really dislike squash merges and prefer rebase merges or just a normal merge commit, which makes it clear who merged, when, and why without reliance on github.

I don't have any choice when it comes to python core dev, but here I'd be really sad to see squash merges.

**Comment by tirkarthi** [comment]
My concern on this PR was about multiple commits with same messages "ci tweaks" landing on master's git log and could be done for this PR alone to squash the commits with same message as a single message.

**Comment by cjw296** [comment]
Oh yeah, don't worry about that, will clean all of those up before merge :-)

**Pull request merged**
