### PR TITLE
Support python 2.6

### PR DESCRIPTION
**Pull request by rbtcollins**
Replace set comprehensions with calls to set() and ensure string
formatting has positional format specifiers.

Co-Authored-By: Robert Collins <rbtcollins@hp.com>

### CODE REVIEW

**Comment by carltongibson** [comment]
Can I request a new version with 2.6 support on PyPI? Thanks!

**Comment by rbtcollins** [comment]
Shortly yes. I'm hoping to get my fixed for mock_open with read_data in shortly; @berkerpeksag has promised a review :) Once thats in, I'll backport the most recent fixes and cut a release.

**Comment by esc** [comment]
Do you already know what number the new version will be?

**Comment by snordhausen** [comment]
+1 for Python 2.6 support

The really bad part is that "pip install mock" will install version 1.1 despite the fact that only Python 2.6 is available.

**Comment by Woi** [comment]
I highly appreciate Python 2.6 support, too.

**Pull request merged**
